import { supabase, IS_CONFIGURED } from "./supabase-client.js";
import { canDo } from "./auth.js";

const money = (v) => `₹${Number(v || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const esc = (v = "") => String(v).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
const iso = () => new Date().toISOString().slice(0, 10);
const notice = (file) => `<div class="placeholder-screen"><h2>Connect Supabase first</h2><p>Configure <code>js/config.js</code> and run <code>${file}</code> in Supabase SQL Editor.</p></div>`;
const status = (el, message, bad = false) => { el.textContent = message; el.className = `form-status ${bad ? "error" : "success"}`; };
const options = (rows, selected = "", label = (r) => r.name) => (rows || []).filter((r) => r.active !== false).map((r) => `<option value="${r.id}" ${r.id === selected ? "selected" : ""}>${esc(label(r))}</option>`).join("");

export async function renderExpenseCategoriesScreen(screen, user) {
  if (!IS_CONFIGURED) { screen.innerHTML = notice("db/phase6_automation.sql"); return; }
  const { data: categories, error } = await supabase.from("expense_categories").select("id,name,pl_bucket,active,created_at").order("name");
  if (error) throw error;
  const owner = canDo(user, "edit_masters");
  screen.innerHTML = `<div class="screen-head"><div><h1>Expense Categories</h1><p>Classify every expense for clean daily and P&L reporting.</p></div>${owner ? '<button class="btn btn-primary" id="new-category">+ New category</button>' : ""}</div>
    <div class="card table-wrap"><table class="ledger"><thead><tr><th>Category</th><th>P&L bucket</th><th>Status</th><th></th></tr></thead><tbody>${(categories || []).map((c) => `<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.pl_bucket)}</td><td>${c.active ? '<span class="stamp settled">Active</span>' : '<span class="stamp pending">Inactive</span>'}</td><td>${owner ? `<button class="btn btn-small edit-category" data-id="${c.id}">Edit</button>` : ""}</td></tr>`).join("") || '<tr><td colspan="4">No categories yet.</td></tr>'}</tbody></table></div><div id="category-modal"></div>`;
  screen.querySelector("#new-category")?.addEventListener("click", () => categoryForm(screen, null));
  screen.querySelectorAll(".edit-category").forEach((b) => b.addEventListener("click", () => categoryForm(screen, categories.find((c) => c.id === b.dataset.id))));
}

function categoryForm(screen, row) {
  const mount = screen.querySelector("#category-modal");
  mount.innerHTML = `<div class="modal-backdrop"><form class="modal-card" id="category-form"><button type="button" class="modal-close">×</button><h2>${row ? "Edit expense category" : "New expense category"}</h2><div class="field"><label>Name</label><input name="name" maxlength="80" required value="${esc(row?.name || "")}" /></div><div class="field"><label>P&L bucket</label><select name="bucket"><option value="direct" ${row?.pl_bucket === "direct" ? "selected" : ""}>Direct cost</option><option value="operating" ${!row || row?.pl_bucket === "operating" ? "selected" : ""}>Operating expense</option><option value="other" ${row?.pl_bucket === "other" ? "selected" : ""}>Other</option></select></div>${row ? `<div class="field"><label>Status</label><select name="active"><option value="true" ${row.active ? "selected" : ""}>Active</option><option value="false" ${!row.active ? "selected" : ""}>Inactive</option></select></div>` : ""}<div class="form-status"></div><button class="btn btn-primary">${row ? "Save changes" : "Create category"}</button></form></div>`;
  mount.querySelector(".modal-close").addEventListener("click", () => { mount.innerHTML = ""; });
  mount.querySelector("form").addEventListener("submit", async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await supabase.rpc(row ? "update_expense_category_master" : "create_expense_category_master", row ? { p_category_id: row.id, p_name: f.get("name").trim(), p_pl_bucket: f.get("bucket"), p_active: f.get("active") === "true" } : { p_name: f.get("name").trim(), p_pl_bucket: f.get("bucket") }); if (result.error) { status(mount.querySelector(".form-status"), result.error.message, true); return; } await renderExpenseCategoriesScreen(screen, window.__appUser); });
}

export async function renderUsersScreen(screen, user) {
  if (!IS_CONFIGURED) { screen.innerHTML = notice("db/phase6_automation.sql"); return; }
  if (!canDo(user, "manage_users")) { screen.innerHTML = '<div class="placeholder-screen"><h2>Owner access required</h2><p>User profiles and roles are managed by the Owner.</p></div>'; return; }
  const { data: users, error } = await supabase.from("users").select("id,auth_id,name,role,active,created_at").order("name"); if (error) throw error;
  screen.innerHTML = `<div class="screen-head"><div><h1>Users</h1><p>App profiles determine what each signed-in person can do.</p></div><button class="btn btn-primary" id="new-user">+ Add profile</button></div><div class="card"><p class="muted">Create or invite the person in Supabase Authentication first, then paste that Auth User ID here. This screen never handles passwords.</p></div><div class="card table-wrap"><table class="ledger"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Auth user ID</th><th></th></tr></thead><tbody>${(users || []).map((u) => `<tr><td><strong>${esc(u.name)}</strong></td><td>${esc(u.role)}</td><td>${u.active ? '<span class="stamp settled">Active</span>' : '<span class="stamp pending">Inactive</span>'}</td><td><small>${esc(u.auth_id)}</small></td><td><button class="btn btn-small edit-user" data-id="${u.id}">Edit</button></td></tr>`).join("") || '<tr><td colspan="5">No user profiles yet.</td></tr>'}</tbody></table></div><div id="user-modal"></div>`;
  screen.querySelector("#new-user").addEventListener("click", () => userForm(screen, null)); screen.querySelectorAll(".edit-user").forEach((b) => b.addEventListener("click", () => userForm(screen, users.find((u) => u.id === b.dataset.id))));
}

function userForm(screen, row) {
  const mount = screen.querySelector("#user-modal");
  mount.innerHTML = `<div class="modal-backdrop"><form class="modal-card" id="user-form"><button type="button" class="modal-close">×</button><h2>${row ? "Edit user profile" : "Add user profile"}</h2>${!row ? '<div class="field"><label>Supabase Auth User ID</label><input name="auth_id" pattern="[0-9a-fA-F-]{36}" required placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" /></div>' : ""}<div class="field"><label>Name</label><input name="name" maxlength="80" required value="${esc(row?.name || "")}" /></div><div class="field"><label>Role</label><select name="role">${["owner", "manager", "staff"].map((role) => `<option value="${role}" ${row?.role === role ? "selected" : ""}>${role[0].toUpperCase() + role.slice(1)}</option>`).join("")}</select></div>${row ? `<div class="field"><label>Status</label><select name="active"><option value="true" ${row.active ? "selected" : ""}>Active</option><option value="false" ${!row.active ? "selected" : ""}>Inactive</option></select></div>` : ""}<div class="form-status"></div><button class="btn btn-primary">${row ? "Save changes" : "Create profile"}</button></form></div>`;
  mount.querySelector(".modal-close").addEventListener("click", () => { mount.innerHTML = ""; }); mount.querySelector("form").addEventListener("submit", async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const res = await supabase.rpc(row ? "update_app_user_profile" : "create_app_user_profile", row ? { p_user_id: row.id, p_name: f.get("name").trim(), p_role: f.get("role"), p_active: f.get("active") === "true" } : { p_auth_id: f.get("auth_id").trim(), p_name: f.get("name").trim(), p_role: f.get("role") }); if (res.error) { status(mount.querySelector(".form-status"), res.error.message, true); return; } await renderUsersScreen(screen, window.__appUser); });
}

function isDue(row, kind, date = new Date()) { const last = row.last_run_date || row.last_paid_date; if (kind === "salary") return (!last || last.slice(0, 7) !== iso().slice(0, 7)) && date.getDate() >= row.payday; if (row.cadence === "monthly") return (!last || last.slice(0, 7) !== iso().slice(0, 7)) && date.getDate() >= row.due_day; return (!last || (Date.parse(iso()) - Date.parse(last)) / 86400000 >= 7) && date.getDay() === row.due_day; }

export async function renderAutomationScreen(screen, user) {
  if (!IS_CONFIGURED) { screen.innerHTML = notice("db/phase6_automation.sql"); return; }
  const allowed = canDo(user, "money_transfer"); const since = new Date(Date.now() - 14 * 86400000).toISOString().slice(0, 10);
  const [categoriesQ, accountsQ, recurringQ, salariesQ, stockQ, purchasesQ, closingsQ] = await Promise.all([
    supabase.from("expense_categories").select("id,name,active").order("name"), supabase.from("accounts").select("id,name,active").order("name"), supabase.from("recurring_expenses").select("*").order("name"), supabase.from("salary_profiles").select("*").order("employee_name"), supabase.from("current_stock").select("item_id,name,unit,quantity,reorder_level").order("name"), supabase.from("purchase_items").select("item_id,quantity,transactions!inner(txn_date,txn_type)").eq("transactions.txn_type", "purchase").gte("transactions.txn_date", since), supabase.from("monthly_closings").select("*").order("period_start", { ascending: false }).limit(6)
  ]);
  const err = [categoriesQ, accountsQ, recurringQ, salariesQ, stockQ, purchasesQ, closingsQ].find((q) => q.error)?.error; if (err) throw err;
  const recurring = recurringQ.data || [], salaries = salariesQ.data || [], stock = stockQ.data || [], low = stock.filter((s) => Number(s.quantity) <= Number(s.reorder_level));
  const bought = new Map(); (purchasesQ.data || []).forEach((p) => bought.set(p.item_id, (bought.get(p.item_id) || 0) + Number(p.quantity))); const suggestions = stock.map((s) => ({ ...s, suggested: Math.max(0, Number(s.reorder_level) + (bought.get(s.item_id) || 0) / 14 - Number(s.quantity)) })).filter((s) => s.suggested > 0.01);
  const dueRec = recurring.filter((r) => isDue(r, "recurring")), dueSalary = salaries.filter((s) => isDue(s, "salary")); const backupAt = localStorage.getItem("tvp-last-backup-at"), backupOld = !backupAt || Date.now() - Date.parse(backupAt) > 7 * 86400000;
  screen.innerHTML = `<div class="screen-head"><div><h1>Automation</h1><p>Actionable checks are calculated from live records; posting still stays deliberate and auditable.</p></div>${allowed ? '<button class="btn btn-primary" id="enable-notifications">Enable browser alerts</button>' : ""}</div>
  <div class="report-kpis"><div><span>Due recurring</span><strong>${dueRec.length}</strong></div><div><span>Due salaries</span><strong>${dueSalary.length}</strong></div><div><span>Low stock</span><strong>${low.length}</strong></div><div><span>Backup</span><strong>${backupOld ? "Due" : "Current"}</strong></div></div>
  ${backupOld ? '<div class="card automation-alert"><strong>Backup reminder:</strong> no backup has been recorded in the last 7 days. <a href="#/backup">Create one now</a>.</div>' : ""}
  <div class="grid grid-2"><div class="card"><div class="card-title">Next-day purchase suggestions</div><p class="muted">Target = reorder level + average daily purchases over 14 days.</p><div class="table-wrap"><table class="ledger"><thead><tr><th>Item</th><th class="num">Stock</th><th class="num">Buy</th></tr></thead><tbody>${suggestions.map((s) => `<tr><td>${esc(s.name)}<br><small>${esc(s.unit)}</small></td><td class="num">${Number(s.quantity).toFixed(2)}</td><td class="num"><strong>${s.suggested.toFixed(2)}</strong></td></tr>`).join("") || '<tr><td colspan="3">No purchase suggestion today.</td></tr>'}</tbody></table></div></div><div class="card"><div class="card-title">Low-stock alerts</div><div class="table-wrap"><table class="ledger"><thead><tr><th>Item</th><th class="num">On hand</th><th class="num">Reorder at</th></tr></thead><tbody>${low.map((s) => `<tr><td>${esc(s.name)}</td><td class="num negative">${Number(s.quantity).toFixed(2)}</td><td class="num">${Number(s.reorder_level).toFixed(2)}</td></tr>`).join("") || '<tr><td colspan="3">All stock is above the reorder level.</td></tr>'}</tbody></table></div></div></div>
  <div class="grid grid-2 automation-sections"><div class="card"><div class="screen-head"><div><div class="card-title">Recurring expenses</div><p class="muted">Post only when due; each run creates a normal expense and audit entry.</p></div>${allowed ? '<button class="btn btn-small" id="new-recurring">+ Schedule</button>' : ""}</div><div class="table-wrap"><table class="ledger"><thead><tr><th>Name</th><th>Schedule</th><th class="num">Amount</th><th></th></tr></thead><tbody>${recurring.map((r) => `<tr><td>${esc(r.name)}</td><td>${esc(r.cadence)} ${r.due_day}</td><td class="num">${money(r.amount)}</td><td>${allowed && isDue(r, "recurring") ? `<button class="btn btn-small run-recurring" data-id="${r.id}">Record</button>` : (isDue(r, "recurring") ? "Due" : "Current")}</td></tr>`).join("") || '<tr><td colspan="4">No recurring expenses scheduled.</td></tr>'}</tbody></table></div></div><div class="card"><div class="screen-head"><div><div class="card-title">Salary tracking</div><p class="muted">One payment per employee each month.</p></div>${allowed ? '<button class="btn btn-small" id="new-salary">+ Salary profile</button>' : ""}</div><div class="table-wrap"><table class="ledger"><thead><tr><th>Employee</th><th>Payday</th><th class="num">Amount</th><th></th></tr></thead><tbody>${salaries.map((s) => `<tr><td>${esc(s.employee_name)}</td><td>${s.payday}</td><td class="num">${money(s.monthly_amount)}</td><td>${allowed && isDue(s, "salary") ? `<button class="btn btn-small run-salary" data-id="${s.id}">Pay</button>` : (isDue(s, "salary") ? "Due" : "Current")}</td></tr>`).join("") || '<tr><td colspan="4">No salary profiles yet.</td></tr>'}</tbody></table></div></div></div>
  <div class="card"><div class="screen-head"><div><div class="card-title">Monthly closing</div><p class="muted">Save an immutable financial snapshot after the month has been checked.</p></div>${allowed ? '<button class="btn btn-small" id="close-month">Close current month</button>' : ""}</div><div class="table-wrap"><table class="ledger"><thead><tr><th>Month</th><th class="num">Sales</th><th class="num">Purchases</th><th class="num">Expenses</th><th class="num">Wastage</th></tr></thead><tbody>${(closingsQ.data || []).map((c) => `<tr><td>${esc(c.period_start)}</td><td class="num">${money(c.sales_total)}</td><td class="num">${money(c.purchase_total)}</td><td class="num">${money(c.expense_total)}</td><td class="num">${money(c.wastage_total)}</td></tr>`).join("") || '<tr><td colspan="5">No monthly closing has been saved.</td></tr>'}</tbody></table></div></div><div id="automation-modal"></div>`;
  screen.querySelector("#enable-notifications")?.addEventListener("click", async () => { if (!("Notification" in window)) { window.alert("Browser notifications are not supported here."); return; } const permission = await Notification.requestPermission(); if (permission === "granted") new Notification("Tasty Vadapav alerts enabled", { body: `${dueRec.length + dueSalary.length + low.length} live checks need attention.` }); });
  screen.querySelector("#new-recurring")?.addEventListener("click", () => scheduleForm(screen, "recurring", categoriesQ.data, accountsQ.data)); screen.querySelector("#new-salary")?.addEventListener("click", () => scheduleForm(screen, "salary", categoriesQ.data, accountsQ.data));
  screen.querySelectorAll(".run-recurring").forEach((b) => b.addEventListener("click", () => runAutomation("record_recurring_expense", { p_recurring_id: b.dataset.id, p_txn_date: iso() }, screen))); screen.querySelectorAll(".run-salary").forEach((b) => b.addEventListener("click", () => runAutomation("record_salary_payment", { p_salary_profile_id: b.dataset.id, p_txn_date: iso() }, screen)));
  screen.querySelector("#close-month")?.addEventListener("click", async () => { const notes = window.prompt("Month-close notes (optional):"); if (notes === null) return; await runAutomation("close_monthly_period", { p_period_start: iso().slice(0, 7) + "-01", p_notes: notes }, screen); });
}

function scheduleForm(screen, type, categories, accounts) { const mount = screen.querySelector("#automation-modal"), recurring = type === "recurring"; mount.innerHTML = `<div class="modal-backdrop"><form class="modal-card" id="schedule-form"><button type="button" class="modal-close">×</button><h2>${recurring ? "Schedule recurring expense" : "Add salary profile"}</h2><div class="field"><label>${recurring ? "Name" : "Employee name"}</label><input name="name" required maxlength="80" /></div><div class="field"><label>Expense category</label><select name="category" required><option value="">Choose</option>${options(categories)}</select></div><div class="field"><label>Paid from</label><select name="account" required><option value="">Choose</option>${options(accounts)}</select></div><div class="field"><label>${recurring ? "Amount" : "Monthly amount"}</label><input name="amount" type="number" min="0.01" step="0.01" required /></div>${recurring ? '<div class="field"><label>Cadence</label><select name="cadence"><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></div><div class="field"><label>Due day (1–31 monthly; 0–6 weekly, Sunday 0)</label><input name="day" type="number" min="0" max="31" value="1" required /></div>' : '<div class="field"><label>Monthly payday (1–31)</label><input name="day" type="number" min="1" max="31" value="1" required /></div>'}<div class="form-status"></div><button class="btn btn-primary">Save</button></form></div>`; mount.querySelector(".modal-close").addEventListener("click", () => { mount.innerHTML = ""; }); mount.querySelector("form").addEventListener("submit", async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const args = recurring ? { p_name: f.get("name").trim(), p_category_id: f.get("category"), p_paid_from_account_id: f.get("account"), p_amount: Number(f.get("amount")), p_cadence: f.get("cadence"), p_due_day: Number(f.get("day")) } : { p_employee_name: f.get("name").trim(), p_category_id: f.get("category"), p_paid_from_account_id: f.get("account"), p_monthly_amount: Number(f.get("amount")), p_payday: Number(f.get("day")) }; const r = await supabase.rpc(recurring ? "create_recurring_expense" : "create_salary_profile", args); if (r.error) { status(mount.querySelector(".form-status"), r.error.message, true); return; } await renderAutomationScreen(screen, window.__appUser); }); }
async function runAutomation(fn, args, screen) { const r = await supabase.rpc(fn, args); if (r.error) { window.alert(r.error.message); return; } await renderAutomationScreen(screen, window.__appUser); }
