import { toast, confirmDialog, promptDialog, friendlyError, setButtonLoading } from "./ui.js";
import { supabase, IS_CONFIGURED } from "./supabase-client.js";
import { loadMasterRelations, itemIdsForPurchaseCategory, expenseItemIdsForCategory, salesChannelsForItem, purchaseCategoriesForItem, expenseCategoriesForItem } from "./master-relations.js";

const TYPES=[
 {key:"sales",label:"Sales",description:"Forecast by sales channel, with optional item drill-down."},
 {key:"purchase",label:"Purchases",description:"Forecast by purchase category; all linked items can be entered together."},
 {key:"expense",label:"Expenses",description:"Budget an expense category, optionally by its linked expense items."},
 {key:"wastage",label:"Wastage",description:"Forecast wastage by item."},
];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const num=v=>Math.max(0,Number(v||0));
const monthStart=v=>{const d=new Date(`${v||new Date().toISOString().slice(0,7)}-01T00:00:00`);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`;};
const monthInput=v=>{const d=v?new Date(`${v}T00:00:00`):new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;};
const monthLabel=v=>new Date(`${v}T00:00:00`).toLocaleDateString("en-IN",{month:"long",year:"numeric"});

function searchableList(id,name,items,selected="",placeholder="Type to search…"){
 const selectedName=(items||[]).find(x=>x.id===selected)?.name||"";
 return `<div class="search-picker"><input id="${id}-search" data-picker-search="${id}" placeholder="${placeholder}" autocomplete="off" value="${esc(selectedName)}"><select id="${id}" name="${name}" data-picker-select="${id}" required><option value="">Select</option>${items.map(x=>`<option value="${x.id}" ${selected===x.id?"selected":""}>${esc(x.name)}</option>`).join("")}</select></div>`;
}

export async function renderBudgetScreen(screen,user){
 if(!IS_CONFIGURED){screen.innerHTML=`<div class="placeholder-screen"><h2>Budget & Forecasting</h2><p>Connect Supabase first.</p></div>`;return;}
 if(!user||!['owner','manager'].includes(user.role)){screen.innerHTML=`<div class="placeholder-screen"><h2>Budget & Forecasting</h2><p>Only Owner and Manager can manage budgets.</p></div>`;return;}
 const [{data:items,error:itemErr},rel]=await Promise.all([supabase.from("items").select("id,name,unit,last_purchase_rate,master_rate,active").eq("active",true).order("name"),loadMasterRelations()]);
 if(itemErr)throw itemErr;
 const state={month:monthInput(),type:"sales",versionId:null,status:null,lines:[],items:items||[],rel};
 screen.innerHTML=`<div class="screen-head"><div><h1>Budget & Forecasting</h1><p>Forecasts use the universal Channel → Item and Category → Item relationships.</p></div><div class="button-row"><button class="btn" id="budget-refresh">Refresh</button><button class="btn btn-primary" id="budget-new">New Draft</button></div></div><div class="card"><div class="form-grid"><label>Budget month<input id="budget-month" type="month" value="${state.month}"></label><label>Budget type<select id="budget-type">${TYPES.map(t=>`<option value="${t.key}">${t.label}</option>`).join("")}</select></label><label>Version<select id="budget-version"><option value="">No version loaded</option></select></label></div><div id="budget-status" class="muted budget-status"></div></div><div id="budget-builder"></div>`;
 const monthEl=screen.querySelector("#budget-month"),typeEl=screen.querySelector("#budget-type"),versionEl=screen.querySelector("#budget-version"),builder=screen.querySelector("#budget-builder"),statusEl=screen.querySelector("#budget-status");
 async function loadVersions(){state.month=monthEl.value;state.type=typeEl.value;const period=monthStart(state.month);const {data:periods,error:pe}=await supabase.from("budget_periods").select("id").eq("month_start",period).limit(1);if(pe)throw pe;let versions=[];if(periods?.[0]){const {data,error}=await supabase.from("budget_versions").select("id,version_no,status,notes,created_at,activated_at").eq("budget_period_id",periods[0].id).eq("budget_type",state.type).order("version_no",{ascending:false});if(error)throw error;versions=data||[];}versionEl.innerHTML=`<option value="">Select version</option>${versions.map(v=>`<option value="${v.id}">v${v.version_no} — ${v.status}</option>`).join("")}`;const active=versions.find(v=>v.status==="active")||versions[0];if(active){versionEl.value=active.id;await loadVersion(active.id);}else{state.versionId=null;state.status=null;state.lines=[];renderBuilder();}statusEl.textContent=versions.length?`${monthLabel(period)} · ${versions.length} version${versions.length===1?"":"s"}`:`${monthLabel(period)} · No budget created yet`;}
 async function loadVersion(id){const [{data:v,error:ve},{data:lines,error:le}]=await Promise.all([supabase.from("budget_versions").select("id,version_no,status,notes,budget_type").eq("id",id).single(),supabase.from("budget_lines").select("id,item_id,category_id,sales_channel_id,purchase_category_id,description,quantity,rate,amount,sort_order").eq("budget_version_id",id).order("sort_order")]);if(ve)throw ve;if(le)throw le;state.versionId=id;state.status=v.status;state.lines=(lines||[]).map(l=>({...l,quantity:num(l.quantity),rate:num(l.rate),amount:num(l.amount)}));renderBuilder(v);}
 const defaultRate=item=>state.type==="purchase"?num(item?.master_rate??item?.last_purchase_rate):0;
 function renderBuilder(version=null){const readOnly=["active","archived"].includes(state.status);const type=TYPES.find(t=>t.key===state.type);builder.innerHTML=`<div class="card"><div class="screen-head budget-builder-head"><div><h2>${type.label} Budget</h2><p>${type.description}</p></div><div class="button-row">${state.versionId&&!readOnly?`<button class="btn" id="budget-add-line">+ Add line</button><button class="btn btn-primary" id="budget-save">Save draft</button><button class="btn" id="budget-activate">Activate</button>`:""}</div></div>${!state.versionId?`<div class="empty-state"><strong>No ${type.label.toLowerCase()} budget yet.</strong><p>Click New Draft to start.</p></div>`:`<div class="table-wrap"><table class="ledger"><thead><tr><th>Context</th><th>Item</th><th>Qty</th><th>Unit</th><th>Forecast Rate</th><th class="num">Budget</th><th></th></tr></thead><tbody id="budget-lines"></tbody><tfoot><tr><th colspan="5">Total</th><th class="num" id="budget-total">${money(state.lines.reduce((s,l)=>s+num(l.quantity)*num(l.rate),0))}</th><th></th></tr></tfoot></table></div><div class="form-grid budget-notes-wrap"><label>Version notes<textarea id="budget-notes" rows="2" ${readOnly?"disabled":""}>${esc(version?.notes||"")}</textarea></label></div><p class="muted">${readOnly?`This version is ${state.status}. Create a new draft to make changes.`:"Forecast rates are budget-only and never change Item Master rates."}</p>`}</div>`;if(!state.versionId)return;const body=builder.querySelector("#budget-lines");body.innerHTML=state.lines.map((l,i)=>lineHtml(l,i,readOnly)).join("")||`<tr><td colspan="7" class="muted">No lines yet.</td></tr>`;if(!readOnly)wire(body);builder.querySelector("#budget-add-line")?.addEventListener("click",()=>{state.lines.push({item_id:null,category_id:null,sales_channel_id:null,purchase_category_id:null,quantity:0,rate:0,sort_order:state.lines.length});renderBuilder(version);});builder.querySelector("#budget-save")?.addEventListener("click",saveDraft);builder.querySelector("#budget-activate")?.addEventListener("click",activateVersion);}
 function lineHtml(l,idx,ro){
  const type=state.type;const item=state.items.find(i=>i.id===l.item_id);
  if(type==="sales"){
    const linked=l.sales_channel_id?new Set(state.rel.salesMap.filter(x=>x.sales_channel_id===l.sales_channel_id).map(x=>x.item_id)):null;
    const candidates=linked?state.items.filter(i=>linked.has(i.id)):state.items;
    return `<tr><td>${searchableList(`sales-context-${idx}`,"sales_channel",state.rel.channels,l.sales_channel_id,"Search channel…")}</td><td>${searchableList(`sales-item-${idx}`,"item_id",candidates,l.item_id,"Search item…").replace(' required','')}</td><td><input data-field="quantity" data-index="${idx}" type="number" min="0" step="0.001" value="${l.quantity}" ${ro?"disabled":""}></td><td>${esc(item?.unit||"—")}</td><td><input data-field="rate" data-index="${idx}" type="number" min="0" step="0.01" value="${l.rate}" ${ro?"disabled":""}></td><td class="num">${money(num(l.quantity)*num(l.rate))}</td><td>${ro?"":`<button class="btn btn-danger-outline" data-remove="${idx}">Remove</button>`}</td></tr>`;
  }
  if(type==="purchase"){
    const linked=itemIdsForPurchaseCategory(state.rel,l.purchase_category_id);const candidates=l.purchase_category_id?state.items.filter(i=>linked.has(i.id)):state.items;
    return `<tr><td>${searchableList(`purchase-context-${idx}`,"purchase_category_id",state.rel.purchaseCategories,l.purchase_category_id,"Search purchase category…")}</td><td>${searchableList(`purchase-item-${idx}`,"item_id",candidates,l.item_id,"Search item…").replace(' required','')}</td><td><input data-field="quantity" data-index="${idx}" type="number" min="0" step="0.001" value="${l.quantity}" ${ro?"disabled":""}></td><td>${esc(item?.unit||"—")}</td><td><input data-field="rate" data-index="${idx}" type="number" min="0" step="0.01" value="${l.rate}" ${ro?"disabled":""}></td><td class="num">${money(num(l.quantity)*num(l.rate))}</td><td>${ro?"":`<button class="btn btn-danger-outline" data-remove="${idx}">Remove</button>`}</td></tr>`;
  }
  if(type==="expense"){
    const linked=expenseItemIdsForCategory(state.rel,l.category_id);const candidates=l.category_id?state.items.filter(i=>linked.has(i.id)):state.items;
    return `<tr><td>${searchableList(`expense-context-${idx}`,"category_id",state.rel.expenseCategories,l.category_id,"Search expense category…")}</td><td>${searchableList(`expense-item-${idx}`,"item_id",candidates,l.item_id,"Search item…").replace(' required','')}</td><td><input data-field="quantity" data-index="${idx}" type="number" min="0" step="0.001" value="${l.quantity}" ${ro?"disabled":""}></td><td>—</td><td><input data-field="rate" data-index="${idx}" type="number" min="0" step="0.01" value="${l.rate}" ${ro?"disabled":""}></td><td class="num">${money(num(l.quantity)*num(l.rate))}</td><td>${ro?"":`<button class="btn btn-danger-outline" data-remove="${idx}">Remove</button>`}</td></tr>`;
  }
  return `<tr><td>Item</td><td>${searchableList(`wastage-item-${idx}`,"item_id",state.items,l.item_id,"Search item…")}</td><td><input data-field="quantity" data-index="${idx}" type="number" min="0" step="0.001" value="${l.quantity}" ${ro?"disabled":""}></td><td>${esc(item?.unit||"—")}</td><td><input data-field="rate" data-index="${idx}" type="number" min="0" step="0.01" value="${l.rate}" ${ro?"disabled":""}></td><td class="num">${money(num(l.quantity)*num(l.rate))}</td><td>${ro?"":`<button class="btn btn-danger-outline" data-remove="${idx}">Remove</button>`}</td></tr>`;
 }
 function wire(body){
  body.querySelectorAll("[data-field]").forEach(el=>el.addEventListener("input",()=>{const l=state.lines[Number(el.dataset.index)],f=el.dataset.field;l[f]=f==="quantity"||f==="rate"?num(el.value):el.value;renderBuilder();}));
  body.querySelectorAll("[data-picker-select]").forEach(sel=>sel.addEventListener("change",()=>{
    const idx=Number(sel.id.split("-").pop()),l=state.lines[idx],id=sel.value||null;
    if(sel.name==="sales_channel"){l.sales_channel_id=id;if(id&&l.item_id&&!state.rel.salesMap.some(x=>x.sales_channel_id===id&&x.item_id===l.item_id))l.item_id=null;renderBuilder();return;}
    if(sel.name==="purchase_category_id"){l.purchase_category_id=id;if(id&&l.item_id&&!state.rel.purchaseMap.some(x=>x.purchase_category_id===id&&x.item_id===l.item_id))l.item_id=null;renderBuilder();return;}
    if(sel.name==="category_id"){l.category_id=id;if(id&&l.item_id&&!state.rel.expenseMap.some(x=>x.expense_category_id===id&&x.item_id===l.item_id))l.item_id=null;renderBuilder();return;}
    if(sel.name==="item_id"){
      l.item_id=id;
      if(state.type==="sales" && id){const contexts=salesChannelsForItem(state.rel,id);if(!l.sales_channel_id&&contexts.length===1)l.sales_channel_id=contexts[0];}
      if(state.type==="purchase" && id){const contexts=purchaseCategoriesForItem(state.rel,id);if(!l.purchase_category_id&&contexts.length===1)l.purchase_category_id=contexts[0];const it=state.items.find(x=>x.id===id);if(l.rate===0)l.rate=defaultRate(it);}
      if(state.type==="expense" && id){const contexts=expenseCategoriesForItem(state.rel,id);if(!l.category_id&&contexts.length===1)l.category_id=contexts[0];}
      renderBuilder();return;
    }
  }));
  body.querySelectorAll("[data-picker-search]").forEach(inp=>inp.addEventListener("input",()=>{const id=inp.dataset.pickerSearch;const sel=body.querySelector(`#${id}`);const q=inp.value.toLowerCase();[...sel.options].forEach(o=>{if(!o.value)return;o.hidden=!o.text.toLowerCase().includes(q);});}));
  body.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{state.lines.splice(Number(b.dataset.remove),1);renderBuilder();}));
 }
 async function newDraft(){const {data,error}=await supabase.rpc("create_budget_version",{p_month_start:monthStart(monthEl.value),p_budget_type:typeEl.value,p_notes:null,p_lines:[]});if(error)throw error;await loadVersions();versionEl.value=data;await loadVersion(data);}
 async function saveDraft(){if(!state.versionId||state.status!=="draft")return;const notes=builder.querySelector("#budget-notes")?.value||null;const lines=state.lines.map((l,i)=>({item_id:l.item_id,category_id:l.category_id,sales_channel_id:l.sales_channel_id,purchase_category_id:l.purchase_category_id,description:l.description||null,quantity:num(l.quantity),rate:num(l.rate),sort_order:i}));const {error}=await supabase.rpc("replace_budget_version_lines",{p_version_id:state.versionId,p_lines:lines,p_notes:notes});if(error)throw error;await loadVersion(state.versionId);statusEl.textContent="Draft saved.";}
 async function activateVersion(){await saveDraft();const {error}=await supabase.rpc("activate_budget_version",{p_version_id:state.versionId});if(error)throw error;await loadVersions();statusEl.textContent="Budget version activated.";}
 screen.querySelector("#budget-new").onclick=()=>newDraft().catch(e=>toast(friendlyError(e.message),{type:"error"}));screen.querySelector("#budget-refresh").onclick=()=>loadVersions().catch(e=>toast(friendlyError(e.message),{type:"error"}));monthEl.onchange=()=>loadVersions().catch(e=>toast(friendlyError(e.message),{type:"error"}));typeEl.onchange=()=>loadVersions().catch(e=>toast(friendlyError(e.message),{type:"error"}));versionEl.onchange=()=>versionEl.value&&loadVersion(versionEl.value).catch(e=>toast(friendlyError(e.message),{type:"error"}));await loadVersions();
}
